from __future__ import print_function
import time
import openapi_client
from openapi_client.rest import ApiException
from pprint import pprint

# 1. Configure API Client
# The generator creates a configuration object pointing to localhost:8000 by default
configuration = openapi_client.Configuration(
    host = "http://localhost:8000"
)

# 2. Initialize the API Instance
with openapi_client.ApiClient(configuration) as api_client:
    # Create an instance of the API class
    # Note: If you didn't add tags in FastAPI, it defaults to 'DefaultApi'
    api_instance = openapi_client.DefaultApi(api_client)

    # --- TEST 1: LIST QUIZZES ---
    print("\n--- 1. Fetching All Quizzes ---")
    try:
        quizzes = api_instance.list_quizzes_quizzes_get()
        pprint(quizzes)
    except ApiException as e:
        print("Exception when calling DefaultApi->list_quizzes: %s\n" % e)

    # --- TEST 2: CREATE A QUIZ ---
    print("\n--- 2. Creating a New Quiz via SDK ---")
    # Define the input model (QuizCreateRequest)
    # The SDK generates specific classes for inputs
    quiz_request = openapi_client.QuizCreateRequest(
        title="SDK Generated Quiz",
        description="Created programmatically via Python SDK",
        questions=[
            openapi_client.Question(
                text="Is this generated by SDK?",
                options=["Yes", "No"],
                correct_answer="Yes"
            )
        ]
    )

    try:
        new_quiz = api_instance.create_quiz_quizzes_post(quiz_request)
        print("✅ Quiz Created!")
        print(f"ID: {new_quiz.id}")
        print(f"Form URL: {new_quiz.form_url}")
        
        created_id = new_quiz.id
    except ApiException as e:
        print("Exception when calling DefaultApi->create_quiz: %s\n" % e)

    # --- TEST 3: APPROVE QUIZ ---
    if 'created_id' in locals():
        print(f"\n--- 3. Approving Quiz ID: {created_id} ---")
        approve_req = openapi_client.ApproveRequest(
            emails=["71762133026@cit.edu.in"]
        )
        try:
            api_instance.approve_quiz_quizzes_quiz_id_approve_post(created_id, approve_req)
            print("✅ Quiz Approved Successfully via SDK!")
        except ApiException as e:
             print("Exception when calling DefaultApi->approve_quiz: %s\n" % e)