# coding: utf-8

"""
    Google Forms Quiz System

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.quiz_create_request import QuizCreateRequest

class TestQuizCreateRequest(unittest.TestCase):
    """QuizCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QuizCreateRequest:
        """Test QuizCreateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QuizCreateRequest`
        """
        model = QuizCreateRequest()
        if include_optional:
            return QuizCreateRequest(
                title = '',
                description = '',
                questions = [
                    openapi_client.models.question.Question(
                        text = '', 
                        options = [
                            ''
                            ], 
                        correct_answer = '', )
                    ]
            )
        else:
            return QuizCreateRequest(
                title = '',
                questions = [
                    openapi_client.models.question.Question(
                        text = '', 
                        options = [
                            ''
                            ], 
                        correct_answer = '', )
                    ],
        )
        """

    def testQuizCreateRequest(self):
        """Test QuizCreateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
