# coding: utf-8

"""
    Google Forms Quiz System

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_approve_quiz_quizzes_quiz_id_approve_post(self) -> None:
        """Test case for approve_quiz_quizzes_quiz_id_approve_post

        Approve Quiz
        """
        pass

    def test_create_quiz_quizzes_post(self) -> None:
        """Test case for create_quiz_quizzes_post

        Create Quiz
        """
        pass

    def test_delete_quiz_quizzes_quiz_id_delete(self) -> None:
        """Test case for delete_quiz_quizzes_quiz_id_delete

        Delete Quiz
        """
        pass

    def test_get_quiz_quizzes_quiz_id_get(self) -> None:
        """Test case for get_quiz_quizzes_quiz_id_get

        Get Quiz
        """
        pass

    def test_health_check_health_check_get(self) -> None:
        """Test case for health_check_health_check_get

        Health Check
        """
        pass

    def test_list_quizzes_quizzes_get(self) -> None:
        """Test case for list_quizzes_quizzes_get

        List Quizzes
        """
        pass

    def test_read_root_get(self) -> None:
        """Test case for read_root_get

        Read Root
        """
        pass


if __name__ == '__main__':
    unittest.main()
