# coding: utf-8

"""
    Google Forms Quiz System

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.quiz_db import QuizDB

class TestQuizDB(unittest.TestCase):
    """QuizDB unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QuizDB:
        """Test QuizDB
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QuizDB`
        """
        model = QuizDB()
        if include_optional:
            return QuizDB(
                id = '',
                title = '',
                status = 'draft',
                form_url = '',
                form_id = '',
                questions = [
                    openapi_client.models.question.Question(
                        text = '', 
                        options = [
                            ''
                            ], 
                        correct_answer = '', )
                    ],
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return QuizDB(
                title = '',
                form_url = '',
                form_id = '',
                questions = [
                    openapi_client.models.question.Question(
                        text = '', 
                        options = [
                            ''
                            ], 
                        correct_answer = '', )
                    ],
        )
        """

    def testQuizDB(self):
        """Test QuizDB"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
