FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy package files first
COPY package.json .
COPY package-lock.json .

# Install dependencies
RUN npm install

# Copy the source code
COPY . .

# Expose port
EXPOSE 3000

# Start React
CMD ["npm", "start"]